spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

server:
  error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: on_trace_param
  include-exception: false

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    path: /swagger-ui.html
    url: ${springdoc.api-docs.path}
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs